version: '3.8'
services:
  db-mysql:
    image: mysql:5.7.40
    restart: always
    environment:
      - MYSQL_DATABASE=bookstore
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3307:3306"
  # docker compose -f mysql.yml -p mysql up -d